Attempt to enable USB debugging in google_apis_playstore image
When using image `google_apis_playstore` rather than `default`, `adb
-s emulator-$port shell getprop dev.bootcomplete` fails initially with
```
error: device offline
```
then with
```
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
```
This means that USB debugging is not enabled.

I noticed at least once that when using image `default` rather than
`google_apis_playstore` prop `qemu.adb.secure` is not set i.e. the
following output line is missing:
```
emulator: Adding boot property: 'qemu.adb.secure' = '1'
```